sass:
  style: compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "assets/img"
    values:
      image: true

# title: vchewjs
# name: vchewjs
# description: Happy together

# github: https://github.com/vchewjs
# rss: true

# plugins:
#   - rouge
#   - kramdown
#   - jekyll-feed
#   - jekyll-seo-tag
#   - jemoji

# exclude:
#   - script
#   - docs
#   - vendor
#   - Gemfile
#   - Gemfile.lock

# --- 网站信息设置 ---
# 下面填写你的博客标题
title: 前端小白
# 下面填写你的网络常用名
name: vchewjs
# 下面填写你的座右铭或者是个性签名
description: Happy together
# 你博客的 url 地址，比如：https://showzeng.github.io 或者是自定义的域名
url: https://github.com/vchewjs
# 在页尾的版权时间信息，比如：2016-2018，默认是 2018 年
copyright_time: 2018-2020
# 标签页的 logo 及博客的头像，如果你想引用网络图片资源，就取消下面的注解，并填写图片资源的 url 地址
# 或者，推荐的做法是将这两个图片资源下载到本地的 /assets/img/ 文件夹下，且图片名必须命名为 favicon 和 avatar
# favicon:
# avatar:
# --- 网站信息设置 ---



# --- 文章列表页 ---
# 文章列表是否显示摘要
show_excerpt: true
# --- 文章页 ---


# --- 社交链接 ---
# 取消下面的注解，并填写相应的你要开启的社交链接
weibo: https://weibo.com/hngczyxxx
github: https://github.com/vchewjs
# 邮件地址前面带上 mailto:
email: mailto:htmlcss95@163.com
# RSS 订阅
rss: true	
# --- 社交链接 ---


# --- 站点统计 ---
# 如果你想开启站点统计，取消下面一行注解，并填写相应统计运营商给的 id，可支持多个同时开启
site_statistics: true
# cnzz (友盟统计)
cnzz_id: 1279148802
# Baidu (百度统计)
# baidu_id:
# Google Analytics (谷歌统计)
# google_id:
# --- 站点统计 ---


# --- 版权声明 ---
# 禁止复制 (注：启用后仅文章页和关于页禁止复制)
# lock_copy: true
# 禁止右键菜单 (注：为全局设置，启用后所有页面均无法使用右键菜单)
# lock_menu: true
# 复制文本末尾添加版权声明 (注：启用后仅文章页和关于页复制添加版权声明)
# copy_with_declaration: true
# --- 版权声明 ---


# --- 打赏设置 ---
# 开启打赏，取消下面一行注解，并将微信和支付宝的收款二维码放置在 /assets/img/ 文件夹下
# 同时图片的文件名必须为 alipay 和 wechat
reward: true
# 打赏的推广语
reward_description: 如果你觉得本文对你有帮助，不妨请我喝杯咖啡
# --- 打赏设置 ---

# --- 评论设置 ---
# 开启评论，取消下面一行注解，并填写相应评论运营商提供的 id，目前仅支持来必力和 gitment
# comment: true
# # 来必力 uid
# # livere_uid:
# # gitment 用户主，即 GitHub 用户名
# gitment_owner: vchewjs
# # GitHub pages 仓库名，如：vchewjs.github.io
# gitment_repo: vchewjs.github.io
# # gitment 提供的对应 id 和 secret
# gitment_client_id: 97fc3fe0fe00168ee985
# gitment_secret: 94368e427a5bc3322d6b938f154d3a554c495ce5
# --- 评论设置 ---

plugins:
  - rouge
  - kramdown
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji

exclude:
  - script
  - docs
  - vendor
  - Gemfile
  - Gemfile.lock
